/**
 * Writes scripts/question-map-ids.sql: every provision id the question maps
 * (src/lib/question-maps.ts) name, as a temp table scripts/corpus_qa.sql
 * check 20 (question_map_ids_exist) joins against the database. SQL cannot
 * read the TypeScript file, so the list is generated here and committed;
 * scripts/question-maps.test.ts fails when the committed file is stale, so a
 * new map that forgets to regenerate fails `npm test`, not production.
 *
 *   npx tsx scripts/question-map-ids.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { QUESTION_MAPS } from "../src/lib/question-maps";

export const QUESTION_MAP_IDS_SQL = path.join(__dirname, "question-map-ids.sql");

/** The file's content for the current QUESTION_MAPS. Deterministic: map order, then provision order. */
export function renderQuestionMapIdsSql(): string {
  const rows = QUESTION_MAPS.flatMap((m) => m.provisions.map((p) => `  ('${m.key}', '${p.id.replace(/'/g, "''")}')`));
  return [
    "-- GENERATED by scripts/question-map-ids.ts from src/lib/question-maps.ts. Do not edit:",
    "-- run `npx tsx scripts/question-map-ids.ts` after changing QUESTION_MAPS (npm test",
    "-- fails while this file is stale).",
    "--",
    "-- Loaded before scripts/corpus_qa.sql (CI: `psql -f scripts/question-map-ids.sql",
    "-- -f scripts/corpus_qa.sql`; in the SQL editor paste this file first, then",
    "-- corpus_qa.sql, in one run) so check 20 can verify every id exists in provisions.",
    "drop table if exists pg_temp.question_map_ids;",
    "create temp table question_map_ids (map_key text, id text);",
    "insert into question_map_ids (map_key, id) values",
    rows.join(",\n") + ";",
    "",
  ].join("\n");
}

if (require.main === module) {
  writeFileSync(QUESTION_MAP_IDS_SQL, renderQuestionMapIdsSql());
  console.log(`wrote ${QUESTION_MAP_IDS_SQL}`);
}
