/**
 * Writes scripts/question-map-ids.sql: every provision id the question maps
 * (src/lib/question-maps.ts) name, as a temp table scripts/corpus_qa.sql
 * check 20 (question_map_ids_exist) joins against the database. SQL cannot
 * read the TypeScript file, so the list is generated here and committed;
 * scripts/question-maps.test.ts fails when the committed file is stale, so a
 * new map that forgets to regenerate fails `npm test`, not production.
 *
 *   npx tsx scripts/question-map-ids.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { PREMISE_NOTES } from "../src/lib/premise-notes";
import { QUESTION_MAPS } from "../src/lib/question-maps";

export const QUESTION_MAP_IDS_SQL = path.join(__dirname, "question-map-ids.sql");

/**
 * Every (map key, id) pair the maps name: the question maps' rows, then
 * (premise notes, 7 Oct 2026) each premise map's rows under its map key and
 * each note's cited ids under "<map key>:note", without repeats.
 */
export function mapIdRows(): [string, string][] {
  const seen = new Set<string>();
  const out: [string, string][] = [];
  const add = (key: string, id: string) => {
    const k = `${key}\u0000${id}`;
    if (seen.has(k)) return;
    seen.add(k);
    out.push([key, id]);
  };
  for (const m of QUESTION_MAPS) for (const p of m.provisions) add(m.key, p.id);
  for (const n of PREMISE_NOTES) {
    for (const p of n.map.provisions) add(n.map.key, p.id);
    for (const s of n.sentences) for (const id of s.cites) add(`${n.map.key}:note`, id);
  }
  return out;
}

/** The file's content for the current maps and notes. Deterministic: map order, then provision order. */
export function renderQuestionMapIdsSql(): string {
  const rows = mapIdRows().map(([key, id]) => `  ('${key}', '${id.replace(/'/g, "''")}')`);
  return [
    "-- GENERATED by scripts/question-map-ids.ts from src/lib/question-maps.ts. Do not edit:",
    "-- run `npx tsx scripts/question-map-ids.ts` after changing QUESTION_MAPS (npm test",
    "-- fails while this file is stale).",
    "--",
    "-- Loaded before scripts/corpus_qa.sql (CI: `psql -f scripts/question-map-ids.sql",
    "-- -f scripts/corpus_qa.sql`; in the SQL editor paste this file first, then",
    "-- corpus_qa.sql, in one run) so check 20 can verify every id exists in provisions.",
    "drop table if exists pg_temp.question_map_ids;",
    "create temp table question_map_ids (map_key text, id text);",
    "insert into question_map_ids (map_key, id) values",
    rows.join(",\n") + ";",
    "",
  ].join("\n");
}

if (require.main === module) {
  writeFileSync(QUESTION_MAP_IDS_SQL, renderQuestionMapIdsSql());
  console.log(`wrote ${QUESTION_MAP_IDS_SQL}`);
}
