-- GENERATED by scripts/question-map-ids.ts from src/lib/question-maps.ts. Do not edit:
-- run `npx tsx scripts/question-map-ids.ts` after changing QUESTION_MAPS (npm test
-- fails while this file is stale).
--
-- Loaded before scripts/corpus_qa.sql (CI: `psql -f scripts/question-map-ids.sql
-- -f scripts/corpus_qa.sql`; in the SQL editor paste this file first, then
-- corpus_qa.sql, in one run) so check 20 can verify every id exists in provisions.
drop table if exists pg_temp.question_map_ids;
create temp table question_map_ids (map_key text, id text);
insert into question_map_ids (map_key, id) values
  ('engines', 'sec-3-A-II-B'),
  ('engines', 'sec-3-A-II-D-1'),
  ('engines', 'sec-3-B-II-A'),
  ('engines', 'sec-3-B-II-D-1-c'),
  ('engines', 'sec-gp12-I-A'),
  ('engines', 'sec-gp02-I-A'),
  ('engines', 'sec-gp09-I-A'),
  ('engines', 'sec-gp10-I-A'),
  ('engines', 'sec-26-B-I-D'),
  ('engines', 'sec-26-B-I'),
  ('engines', 'sec-26-B-II'),
  ('engines', 'sec-26-C-FEDJJJJ'),
  ('engines', 'sec-jjjj-60.4230'),
  ('engines', 'sec-jjjj-60.4233'),
  ('engines', 'sec-iiii-60.4200'),
  ('engines', 'sec-iiii-60.4204'),
  ('engines', 'sec-iiii-60.4205'),
  ('engines', 'sec-zzzz-63.6585'),
  ('engines', 'sec-zzzz-63.6590'),
  ('engines', 'sec-zzzz-63.6595'),
  ('engines', 'sec-jjjj-60.4248'),
  ('engines', 'sec-3-A-I-B-36');
