/**
 * The review-status badge every summary carries (owner decisions, Brody,
 * 29 Sep, 4 Oct and 9 Oct 2026): the pure helper's rows, the reader
 * panel's markup, and the tooltip the browser adds to it. Since 9 Oct 2026
 * the checked state reads "AI-generated · automated check against source
 * text"; "Reviewed" appears only for a row a person approved.
 *
 *   npm test
 */
import assert from "node:assert/strict";
import { test } from "node:test";
import { JSDOM } from "jsdom";
import {
  formatReviewedDate,
  isHumanReviewer,
  withReviewerKind,
  SUMMARY_BADGE_TITLES,
  summaryPanelHtml,
  summaryStatusBadge,
} from "../src/lib/regulation-pure";
import { fillSummaryBadges, readReaderModel } from "../src/lib/reader-client";
import { renderDocHtml } from "../src/lib/reader-render";
import type { Provision } from "../src/lib/types";

const REVIEWED_TITLE =
  "Written by AI, then checked against the source text by a separate automated AI pass, not by a person. The source text controls; see the Disclaimer page, \u201cWhat AI-generated means\u201d.";
const HUMAN_TITLE =
  "Reviewed by a person against the source text. The source text controls; see the Disclaimer page, \u201cWhat AI-generated means\u201d.";
const PENDING_TITLE = "Generated by AI from the source text and not yet checked. Read the source text.";
const AI = "AI-generated · automated check against source text";

test("approved or edited by the pipeline: the AI-generated label with reviewed_at as MMM d, yyyy in America/Denver", () => {
  assert.deepEqual(summaryStatusBadge({ summary_status: "approved", reviewed_at: "2026-09-17T18:04:10.123+00:00" }), {
    kind: "reviewed",
    label: `${AI} · Sept 17, 2026`,
    compactLabel: AI,
    title: REVIEWED_TITLE,
  });
  assert.deepEqual(
    summaryStatusBadge({ summary_status: "edited", reviewed_at: "2026-09-13T05:33:22.912Z", reviewed_by: "automated pipeline (review.py)" }),
    { kind: "reviewed", label: `${AI} · Sept 12, 2026`, compactLabel: AI, title: REVIEWED_TITLE }
  );
});

test("approved with a null reviewed_at: the label alone, never an empty date", () => {
  assert.deepEqual(summaryStatusBadge({ summary_status: "approved", reviewed_at: null }), {
    kind: "reviewed",
    label: AI,
    compactLabel: AI,
    title: REVIEWED_TITLE,
  });
  assert.equal(summaryStatusBadge({ summary_status: "edited", reviewed_at: "not a date" })!.label, AI);
});

test("a person's approval reads 'Reviewed · <date>'; the pipeline stamp and no stamp never do (9 Oct 2026)", () => {
  const at = "2026-09-17T18:04:10Z";
  const human = summaryStatusBadge({ summary_status: "approved", reviewed_at: at, reviewed_by: "jane@example.com" })!;
  assert.deepEqual(human, { kind: "human", label: "Reviewed · Sept 17, 2026", compactLabel: "Reviewed", title: HUMAN_TITLE });
  // The already-reduced boolean (what crosses to the browser) gives the same answer, with no name anywhere.
  assert.equal(summaryStatusBadge({ summary_status: "edited", reviewed_at: at, reviewed_by_human: true })!.kind, "human");
  for (const stamp of ["automated pipeline (review.py)", "Automated Pipeline", "", "  ", null, undefined]) {
    assert.equal(summaryStatusBadge({ summary_status: "approved", reviewed_at: at, reviewed_by: stamp })!.kind, "reviewed", String(stamp));
  }
  assert.equal(isHumanReviewer("jane@example.com"), true);
  assert.equal(isHumanReviewer("automated pipeline"), false);
  assert.equal(isHumanReviewer(null), false);
  // withReviewerKind drops the name.
  const reduced = withReviewerKind({ id: "x", reviewed_by: "jane@example.com" });
  assert.deepEqual(reduced, { id: "x", reviewed_by_human: true });
  // A pending row never claims human review, whatever reviewed_by says.
  assert.equal(summaryStatusBadge({ summary_status: "pending", reviewed_by: "jane@example.com" })!.kind, "pending");
});

test("no badge, in any state, opens with the bare word 'Reviewed' unless a person approved it", () => {
  const dates = [null, undefined, "", "not a date", "2026-09-17T18:04:10Z", "2026-10-04T15:19:48.366041+00:00"];
  const statuses = ["approved", "edited", "pending", "rejected", null, undefined, "something-else"];
  let seen = 0;
  for (const summary_status of statuses) {
    for (const reviewed_at of dates) {
      const badge = summaryStatusBadge({ summary_status, reviewed_at } as Parameters<typeof summaryStatusBadge>[0]);
      if (!badge) continue;
      seen++;
      assert.doesNotMatch(badge.label, /^Reviewed\b/, `label for ${summary_status}/${reviewed_at}`);
      assert.ok(badge.label.startsWith("AI-generated"), badge.label);
      assert.doesNotMatch(badge.label, /AI reviewed/);
      assert.doesNotMatch(badge.title.replace(/not by a person/i, ""), /human|person|founder|reviewed by/i);
      if (badge.kind === "reviewed") assert.match(badge.title, /automated AI pass, not by a person/);
    }
  }
  assert.ok(seen > 0);
});

test("pending (or no status at all): 'AI-generated · not yet reviewed'", () => {
  const pending = { kind: "pending", label: "AI-generated · not yet reviewed", compactLabel: "AI-generated · not yet reviewed", title: PENDING_TITLE };
  assert.deepEqual(summaryStatusBadge({ summary_status: "pending", reviewed_at: null }), pending);
  // A pending row keeps reviewed_at from an earlier pass: the date is not shown.
  assert.deepEqual(summaryStatusBadge({ summary_status: "pending", reviewed_at: "2026-09-13T05:33:22.912Z" }), pending);
  assert.deepEqual(summaryStatusBadge({ summary_status: null, reviewed_at: null }), pending);
  assert.deepEqual(summaryStatusBadge({}), pending);
});

test("rejected: no badge (the summary is withheld everywhere)", () => {
  assert.equal(summaryStatusBadge({ summary_status: "rejected", reviewed_at: "2026-09-13T05:33:22.912Z" }), null);
});

test("the tooltips are the agreed wording and name the Disclaimer page", () => {
  assert.equal(SUMMARY_BADGE_TITLES.reviewed, REVIEWED_TITLE);
  assert.equal(SUMMARY_BADGE_TITLES.human, HUMAN_TITLE);
  assert.equal(SUMMARY_BADGE_TITLES.pending, PENDING_TITLE);
});

test("formatReviewedDate: AP-style month, the America/Denver day, '' for nothing (Sprint 5)", () => {
  // 01:06 UTC on the 22nd is 19:06 on the 21st in Colorado (MDT, UTC-6).
  assert.equal(formatReviewedDate("2026-09-22T01:06:57.401013+00:00"), "Sept 21, 2026");
  // Midnight UTC in January is 17:00 the evening before (MST, UTC-7).
  assert.equal(formatReviewedDate("2026-01-05T00:00:00Z"), "Jan 4, 2026");
  assert.equal(formatReviewedDate("2026-06-30T23:59:59Z"), "June 30, 2026");
  assert.equal(formatReviewedDate("2026-03-01T06:30:00+00:00"), "Feb 28, 2026");
  // A date-only value is a calendar day, not a UTC midnight to be shifted.
  assert.equal(formatReviewedDate("2026-09-22"), "Sept 22, 2026");
  assert.equal(formatReviewedDate(null), "");
  assert.equal(formatReviewedDate(undefined), "");
  assert.equal(formatReviewedDate(""), "");
  assert.equal(formatReviewedDate("not a date"), "");
});

const base = {
  ai_summary: "A plain-English summary.\n\nSecond paragraph.",
  source_url: "https://example.gov/reg",
};

test("summaryPanelHtml: the badge is the first element in .summary-body, text and state class only", () => {
  const reviewed = summaryPanelHtml({ ...base, summary_status: "approved", reviewed_at: "2026-09-17T18:04:10Z" });
  assert.equal(
    reviewed,
    `<details class="summary-panel"><summary>Plain-English summary</summary>` +
      `<div class="summary-body"><p class="summary-badge is-reviewed">${AI} · Sept 17, 2026</p>` +
      `<p>A plain-English summary.</p><p>Second paragraph.</p></div>` +
      `<div class="summary-status"></div></details>`
  );
  const pending = summaryPanelHtml({ ...base, summary_status: "pending", reviewed_at: null });
  assert.ok(pending.includes(`<div class="summary-body"><p class="summary-badge is-pending">AI-generated · not yet reviewed</p><p>`));
  // No tooltip and no reviewer in the shipped string: the browser adds the title.
  assert.ok(!reviewed.includes("title="));
  assert.ok(!pending.includes("title="));
});

test("summaryPanelHtml: rejected and empty summaries render no panel, so no badge", () => {
  assert.equal(summaryPanelHtml({ ...base, summary_status: "rejected", reviewed_at: "2026-09-17T18:04:10Z" }), "");
  assert.equal(summaryPanelHtml({ ...base, ai_summary: null, summary_status: "approved", reviewed_at: "2026-09-17T18:04:10Z" }), "");
  assert.equal(summaryPanelHtml({ ...base, ai_summary: "  \n\n ", summary_status: "pending", reviewed_at: null }), "");
});

function row(id: string, parent_id: string | null, extra: Partial<Provision> = {}): Provision {
  return {
    id,
    citation: id.split("-").pop()!,
    title: id,
    jurisdiction_level: "state",
    issuing_body: "TEST",
    parent_id,
    full_text: `<p>${id}</p>`,
    ai_summary: null,
    source_url: null,
    last_verified_date: null,
    is_public: false,
    sort_order: 0,
    summary_status: null,
    reviewed_at: null,
    ...extra,
  };
}

test("fillSummaryBadges: the browser sets each badge's tooltip from its state class, once", () => {
  const all = [
    row("sec-t-top-REG-t", null, { source_url: "https://example.gov/t" }),
    row("sec-t-A-PART-A", "sec-t-top-REG-t", { ai_summary: "Checked.", summary_status: "approved", reviewed_at: "2026-09-17T18:04:10Z" }),
    row("sec-t-A-I", "sec-t-A-PART-A", { ai_summary: "Not yet.", summary_status: "pending" }),
    row("sec-t-A-II", "sec-t-A-PART-A", { ai_summary: "Withheld.", summary_status: "rejected", reviewed_at: "2026-09-17T18:04:10Z" }),
    row("sec-t-A-III", "sec-t-A-PART-A"),
  ];
  const dom = new JSDOM(`<!doctype html><div id="doc">${renderDocHtml(all)}</div>`);
  const doc = dom.window.document.getElementById("doc")!;
  const model = readReaderModel(doc);
  const badges = () => Array.from(doc.querySelectorAll(".summary-badge")).map((b) => [b.textContent, b.getAttribute("title")]);
  assert.deepEqual(badges(), [
    [`${AI} · Sept 17, 2026`, null],
    ["AI-generated · not yet reviewed", null],
  ]);
  fillSummaryBadges(model);
  assert.deepEqual(badges(), [
    [`${AI} · Sept 17, 2026`, REVIEWED_TITLE],
    ["AI-generated · not yet reviewed", PENDING_TITLE],
  ]);
  // Every panel body opens with its badge; the rejected and empty rows have no panel at all.
  for (const body of Array.from(doc.querySelectorAll(".summary-body"))) {
    assert.ok(body.firstElementChild?.classList.contains("summary-badge"), "badge first");
  }
  assert.equal(doc.querySelectorAll("details.summary-panel").length, 2);
  // Idempotent: a second pass changes nothing.
  fillSummaryBadges(model);
  assert.equal(doc.querySelectorAll(".summary-badge[title]").length, 2);
});
