-- GENERATED by scripts/test-method-slugs.ts from src/data/test-methods.json. Do not edit:
-- run `npx tsx scripts/test-method-slugs.ts` after changing the entries (npm test fails
-- while this file is stale).
--
-- Loaded before scripts/corpus_qa.sql (CI: `psql -f scripts/question-map-ids.sql
-- -f scripts/test-method-slugs.sql -f scripts/corpus_qa.sql`; in the SQL editor paste
-- this file ahead of corpus_qa.sql, in one run) so checks 26 and 27 can verify every
-- /test-methods/<slug> link in provisions.full_text and every provision_method_citations
-- row names a slug the data file has.
drop table if exists pg_temp.test_method_slugs;
create temp table test_method_slugs (slug text primary key);
insert into test_method_slugs (slug) values
  ('method-1'),
  ('method-1a'),
  ('method-2'),
  ('method-2a'),
  ('method-2d'),
  ('method-3'),
  ('method-3a'),
  ('method-3b'),
  ('method-3c'),
  ('method-4'),
  ('method-5'),
  ('method-6'),
  ('method-7e'),
  ('method-9'),
  ('method-10'),
  ('method-15'),
  ('method-16'),
  ('method-16a'),
  ('method-18'),
  ('method-19'),
  ('method-21'),
  ('method-22'),
  ('method-24'),
  ('method-25a'),
  ('method-27'),
  ('method-301'),
  ('method-320'),
  ('ps-2'),
  ('ps-8'),
  ('ps-9');
