/**
 * Writes scripts/test-method-slugs.sql: every Test Methods slug in
 * src/data/test-methods.json, as a temp table scripts/corpus_qa.sql checks
 * 26 and 27 (test_method_links_resolve, test_method_citations_dangle) join
 * against the database -- the same arrangement as scripts/question-map-ids.ts
 * for check 20. SQL cannot read the JSON file, so the list is generated here
 * and committed; scripts/test-methods.test.ts fails when the committed file
 * is stale, so a new entry that forgets to regenerate fails `npm test`, not
 * the qa job.
 *
 *   npx tsx scripts/test-method-slugs.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { TEST_METHODS } from "../src/data/test-methods";

export const TEST_METHOD_SLUGS_SQL = path.join(__dirname, "test-method-slugs.sql");

/** The file's content for the current entries. Deterministic: file order. */
export function renderTestMethodSlugsSql(): string {
  const rows = TEST_METHODS.map((m) => `  ('${m.slug.replace(/'/g, "''")}')`);
  return [
    "-- GENERATED by scripts/test-method-slugs.ts from src/data/test-methods.json. Do not edit:",
    "-- run `npx tsx scripts/test-method-slugs.ts` after changing the entries (npm test fails",
    "-- while this file is stale).",
    "--",
    "-- Loaded before scripts/corpus_qa.sql (CI: `psql -f scripts/question-map-ids.sql",
    "-- -f scripts/test-method-slugs.sql -f scripts/corpus_qa.sql`; in the SQL editor paste",
    "-- this file ahead of corpus_qa.sql, in one run) so checks 26 and 27 can verify every",
    "-- /test-methods/<slug> link in provisions.full_text and every provision_method_citations",
    "-- row names a slug the data file has.",
    "drop table if exists pg_temp.test_method_slugs;",
    "create temp table test_method_slugs (slug text primary key);",
    "insert into test_method_slugs (slug) values",
    rows.join(",\n") + ";",
    "",
  ].join("\n");
}

if (require.main === module) {
  writeFileSync(TEST_METHOD_SLUGS_SQL, renderTestMethodSlugsSql());
  console.log(`wrote ${TEST_METHOD_SLUGS_SQL}`);
}
