-- =====================================================================
-- EssentialRegs Phase 2 — review queue + changelog tables.
-- Paste this WHOLE file into Supabase → SQL Editor → New query → Run.
-- Safe to run more than once.
-- =====================================================================

-- 004_review.sql — admin review queue + changelog
--
-- Run this once in the Supabase SQL Editor (or via the MCP connector) AFTER
-- schema.sql, 002_subscriptions.sql and 003_search.sql. Safe to re-run:
-- every statement is IF NOT EXISTS / DROP IF EXISTS + CREATE, or wrapped in
-- a guard where that's not directly available (the CHECK constraint below).
--
-- What this adds:
--   1. Review-tracking columns on `provisions`: summary_status (pending /
--      approved / edited / rejected), reviewed_by, reviewed_at, and
--      summary_original (the AI-generated text as first written, preserved
--      the first time an admin edits it so an edit can always be diffed
--      against the original AI output).
--   2. `provision_changes` — an append-only changelog row per moderation
--      action (written by the admin server actions using the service-role
--      client), plus a trigger that logs a `text_updated` row whenever the
--      regulatory text itself changes (from any source, not just review).
--   3. RLS on provision_changes: readable by any signed-in user (powers the
--      logged-in view of the public /changelog page), writable by nobody
--      through PostgREST — every insert goes through the service-role admin
--      client from a server action (src/app/admin/review/actions.ts) after
--      an explicit `requireAdmin()` check, or through the trigger function
--      below (SECURITY DEFINER, not subject to RLS).

-- 1. Review-tracking columns on provisions ---------------------------------

alter table provisions add column if not exists summary_status text not null default 'pending';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'provisions_summary_status_check'
  ) then
    alter table provisions
      add constraint provisions_summary_status_check
      check (summary_status in ('pending', 'approved', 'edited', 'rejected'));
  end if;
end $$;

alter table provisions add column if not exists reviewed_by text;
alter table provisions add column if not exists reviewed_at timestamptz;
alter table provisions add column if not exists summary_original text;

create index if not exists provisions_summary_status_idx on provisions (summary_status);

comment on column provisions.summary_status is
  'Moderation state of ai_summary: pending (not yet reviewed), approved (reviewed as-is), edited (reviewer changed the text), rejected (summary withheld from readers). Written only by src/app/admin/review/actions.ts via the service-role client.';
comment on column provisions.summary_original is
  'ai_summary as first generated by the pipeline, preserved the first time a reviewer edits it. Null until the first edit.';

-- 2. Changelog -------------------------------------------------------------

create table if not exists provision_changes (
  id           bigserial primary key,
  provision_id text references provisions(id) on delete cascade,
  change_type  text not null check (
    change_type in ('summary_approved', 'summary_edited', 'summary_rejected', 'text_updated', 'added')
  ),
  note         text,
  created_at   timestamptz not null default now()
);

create index if not exists provision_changes_created_at_idx on provision_changes (created_at desc);

alter table provision_changes enable row level security;

drop policy if exists "authenticated can read changes" on provision_changes;
create policy "authenticated can read changes"
  on provision_changes for select
  to authenticated
  using (true);

-- No insert/update/delete policies for any client role on purpose — see the
-- header comment. Anonymous visitors get zero rows (no select policy for
-- `anon`), which is exactly what /changelog's logged-out state expects.

-- Logs a `text_updated` row whenever full_text changes on an UPDATE of
-- provisions, regardless of what changed it (review actions never touch
-- full_text, so this doesn't double up with the review actions' own
-- summary_approved/edited/rejected inserts).
create or replace function log_provision_text_updated()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if new.full_text is distinct from old.full_text then
    insert into provision_changes (provision_id, change_type)
    values (new.id, 'text_updated');
  end if;
  return new;
end;
$$;

drop trigger if exists provisions_log_text_updated on provisions;
create trigger provisions_log_text_updated
  after update on provisions
  for each row execute function log_provision_text_updated();
